use_frameworks!

platform :ios, '8.0'

target 'QQEffectiveNavigation_Example' do
  pod 'QQEffectiveNavigation', :path => '../'

  target 'QQEffectiveNavigation_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
